### ISSUE TITLE
View composers

### ISSUE THREAD

**Issue by vpratfr** [skyronic/laravel-cookie#1]
Could be rather nice too.

See what I had submitted to the framework, but got rejected:

https://github.com/laravel/framework/pull/18205

Should give you a good basis for a generator of yours

**Comment by skyronic** [comment]
thanks for the suggestion man!

**Comment by vpratfr** [comment]
You could have added an option or an additional command to generate the `ViewComposerServiceProvider` as suggested in my original PR, that's usually needed on each project using a `ViewComposer`
